name: smart_health_guard
description: A full health app with health tools and trackers.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.3
  camera: ^0.10.5+2
  torch_light: ^0.4.0
  csv: ^5.1.0
  fl_chart: ^0.64.0
  cloud_firestore: ^4.9.2
  firebase_core: ^2.30.1
  expandable: ^5.0.1
  stop_watch_timer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/emergency.png
    - assets/fan.png
    - assets/bp.png
    - assets/heart.png
    - assets/family.png
    - assets/sugar.png
    - assets/emergency_alarm.png
    - assets/alarm_sound.mp3
    - assets/smart_home.jpg
    - assets/mic.png
    - assets/bpp.png
    - assets/heart_r.png
    - assets/ff.png
    - assets/med.png
    - assets/med_r.png
    - assets/sugar_r.png
    - assets/ss.png
    - assets/rr.png
    - assets/mm.png
    - assets/jj.png
    - assets/kk.png
    - assets/bmi.png
